<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

$additionalData = $this->getData('WirecardEEAdditionalViewAssignments');
?>
<input type="hidden" id="wirecardee-sepa--confirm-mandate"
       name="wirecardElasticEngine[sepaConfirmMandate]"
       required="required" value=""/>
<div class="wirecardee-sepa--first-name">
    <input class="is--required" id="wirecardee-sepa--first-name" type="text"
           name="wirecardElasticEngine[sepaFirstName]" autocomplete="off"
           required="required" placeholder="<?php echo $this->__('First Name'); ?>"/>
</div>
<div class="wirecardee-sepa--last-name">
    <input class="is--required" id="wirecardee-sepa--last-name" type="text"
           name="wirecardElasticEngine[sepaLastName]" autocomplete="off"
           required="required" placeholder="<?php echo $this->__('Last Name'); ?>"}{/s}"/>
</div>
<div class="wirecardee-sepa--iban">
    <input class="is--required" id="wirecardee-sepa--iban" type="text"
           name="wirecardElasticEngine[sepaIban]" autocomplete="off"
           required="required" placeholder="<?php echo $this->__('IBAN'); ?>"}{/s}"/>
</div>

<?php if ($additionalData['showBic']) : ?>
<div class="wirecardee-sepa--bic">
    <input type="text" id="wirecardee-sepa--bic" name="wirecardElasticEngine[sepaBic]"
           autocomplete="off" placeholder="<?php echo $this->__('BIC'); ?>}{/s}"/>
</div>
<?php endif; ?>
