<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

if (!$this->_wirecardEEHasAdditional)
    return;

$additionalData = $this->getData('WirecardEEAdditionalViewAssignments');

switch ($additionalData["method"]) {
    case 'sepadirectdebit':
        echo $this->getChildHtml("wirecard.additional.sepa");
        break;
}
