<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

/** @var $this WirecardEE_PaymentGateway_Block_Checkout_Success */
?>
<div class="wirecardee_checkout_payment_status">
    <?php echo Mage::helper('catalog')->__('config_status'); ?>: <?php echo $this->getOrderStatusLabel(); ?>

    <?php
    if ($this->getOrderStatusLabel() === Mage_Sales_Model_Order::STATE_PENDING_PAYMENT) {
        echo '<p>' . Mage::helper('catalog')->__('Awaiting payment from Wirecard. You will receive an e-mail once the payment has been finalized.') . '</p>';
    }
    ?>
</div>
