<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

/** @var $this Mage_Payment_Block_Form */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none;">
    <li>
        <label for="wirecardee-eps--bic"><?php echo $this->__('bic_input'); ?></label>
        <div class="input-box">
            <input type="text" id="wirecardee-eps--bic" class="wirecardee--form-field"
                   name="wirecardElasticEngine[epsBic]"
                   autocomplete="off" placeholder="<?php echo $this->__('bic_input'); ?>"/>
        </div>
    </li>
</ul>
