<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

/** @var $this Mage_Payment_Block_Form */

use Wirecard\PaymentSdk\Entity\IdealBic;
$idealBic = new \ReflectionClass(IdealBic::class);
$idealBanks = $idealBic->getConstants();
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none;">
    <li>
        <div class="input-box">
            <select class="is--required" name="wirecardElasticEngine[idealBank]">
                <?php foreach ($idealBanks as $bankKey=>$bankLabel) : ?>
                <option value="<?php echo $bankKey ?>"><?php echo $bankLabel ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
</ul>
