<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

/** @var $this Mage_Payment_Block_Form */
/** @var WirecardEE_PaymentGateway_Model_Payolutioninvoice $payolutionInvoiceModel */

$payolutionInvoiceModel = Mage::getModel('paymentgateway/payolutioninvoice');
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none;">
    <?php
    if (! $payolutionInvoiceModel->showDobForm()) {
        ?>
        <li>
            <label for="wirecardee-payolution--dob-day"
                   class="required"><em>*</em><?php echo $this->__('birthdate_input'); ?></label>
            <div class="input-box customer-dob">
                <div class="dob-month">
                    <input type="text" id="wirecardee-payolution--dob-month"
                           name="wirecardElasticEngine[birthday][month]"
                           title="<?php echo $this->__('birthdate_input_month'); ?>" class="input-text"/>
                    <label
                        for="wirecardee-payolution--dob-month">
                        <?php echo $this->__('birthdate_input_month_format'); ?>
                    </label>
                </div>
                <div class="dob-day">
                    <input type="text" id="wirecardee-payolution--dob-day" name="wirecardElasticEngine[birthday][day]"
                           title="<?php echo $this->__('birthdate_input_day'); ?>" class="input-text"/>
                    <label
                        for="wirecardee-payolution--dob-day">
                        <?php echo $this->__('birthdate_input_day_format'); ?>
                    </label>
                </div>
                <div class="dob-year">
                    <input type="text" id="wirecardee-payolution--dob-year" name="wirecardElasticEngine[birthday][year]"
                           title="<?php echo $this->__('birthdate_input_year'); ?>" class="input-text"/>
                    <label
                        for="wirecardee-payolution--dob-year">
                        <?php echo $this->__('birthdate_input_year_format'); ?>
                    </label>
                </div>
            </div>
        </li>
        <?php
    }

    if ($payolutionInvoiceModel->requiresConsent()) {
        ?>
        <li>
            <input type="checkbox" id="wirecardee-payolution--consent"
                   class="wirecardee--form-field"
                   name="wirecardElasticEngine[payolutionConsent]"
                   required="required" value="confirmed"/>
            <label
                for="wirecardee-payolution--consent"
                class="required"><?php echo $this->__('payolution_consent_text'); ?></label>
        </li>
        <?php
    }
    ?>

</ul>
