<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

/** @var $this Mage_Payment_Block_Form */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none;">
    <li>
        <p class="required"><?php echo $this->__('* Required fields'); ?></p>
        <label for="wirecardee-sepa--first-name" class="required"><em>*</em><?php echo $this->__('First Name'); ?>
        </label>
        <div class="input-box">
            <input class="is--required wirecardee--form-field" id="wirecardee-sepa--first-name" type="text"
                   name="wirecardElasticEngine[sepaFirstName]" autocomplete="off"
                   required="required" placeholder="<?php echo $this->__('First Name'); ?>"/>
        </div>
    </li>
    <li>
        <label for="wirecardee-sepa--last-name" class="required"><?php echo $this->__('Last Name'); ?></label>
        <div class="input-box">
            <input class="is--required wirecardee--form-field" id="wirecardee-sepa--last-name" type="text"
                   name="wirecardElasticEngine[sepaLastName]" autocomplete="off"
                   required="required" placeholder="<?php echo $this->__('Last Name'); ?>"/>
        </div>
    </li>
    <li>
        <label for="wirecardee-sepa--iban" class="required"><?php echo $this->__('IBAN'); ?></label>
        <div class="input-box">
            <input class="is--required wirecardee--form-field" id="wirecardee-sepa--iban" type="text"
                   name="wirecardElasticEngine[sepaIban]" autocomplete="off"
                   required="required" placeholder="<?php echo $this->__('IBAN'); ?>"/>
        </div>
    </li>
    <?php if ($this->getMethod()->getConfigData('show_bic')) : ?>
        <li>
            <label for="wirecardee-sepa--bic"><?php echo $this->__('BIC'); ?></label>
            <div class="input-box">
                <input type="text" id="wirecardee-sepa--bic" class="wirecardee--form-field"
                       name="wirecardElasticEngine[sepaBic]"
                       autocomplete="off" placeholder="<?php echo $this->__('BIC'); ?>"/>
            </div>
        </li>
    <?php endif; ?>
    <li>
        <table border="0" cellpadding="0" cellspacing="0" class="stretch">
            <tr>
                <td class="text11justify">
                    <i><?php echo $this->__("Creditor"); ?></i><br/>
                    <?php echo $this->getMethod()->getConfigData('creditor_name'); ?><br/>
                    <?php echo $this->getMethod()->getConfigData('creditor_street'); ?><br/>
                    <?php echo $this->getMethod()->getConfigData('creditor_zip'); ?> <?php echo $this->getMethod()
                                                                                                     ->getConfigData('creditor_zip'); ?>
                    <br/>
                    <?php echo $this->getMethod()->getConfigData('creditor_country'); ?><br/>
                    <?php echo $this->__('Creditor ID'); ?>: <?php echo $this->getMethod()
                                                                             ->getConfigData('creditor_id'); ?><br/>
                </td>
            </tr>
            <tr>
                <td class="text11">
                    <i><?php echo $this->__('Debtor'); ?></i><br/>
                    <?php echo $this->__('Account owner'); ?>:
                    <span id="wirecardee-sepa--first-last-name" class="first_last_name"></span><br/>
                    <?php echo $this->__('IBAN'); ?>:
                    <span id="wirecardee-sepa--bank-iban"></span><br/>
                    <?php if ($this->getMethod()->getConfigData('show_bic')): ?>
                        <?php echo $this->__('BIC'); ?>:
                        <span id="wirecardee-sepa--bank-bic"></span>
                        <br/>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td class="text11justify" style="text-align: justify; padding: 10px 0;">
                    <?php
                    /** @var Mage_Adminhtml_Block_Abstract $mandateBlock */
                    $mandateBlock = Mage::app()->getLayout()->createBlock('cms/block')
                                        ->setData('block_id', 'wirecardee_sepa_mandate_text');
                    $mandateText  = $mandateBlock->toHtml();

                    if (! $mandateText) {
                        $mandateTextForm = $this->__('I authorize the creditor %1$s to send instructions to my bank to collect one single direct debit from my account. At the same time I instruct my bank to debit my account in accordance with the instructions from the creditor %1$s<br /><br />Note: As part of my rights, I am entitled to a refund under the terms and conditions of my agreement with my bank. A refund must be claimed within 8 weeks starting from the date on which my account was debited.<br /><br />I irrevocably agree that, in the event that the direct debit is not honored, or objection against the direct debit exists, my bank will disclose to the creditor %1$s my full name, address and date of birth.');

                        $mandateText = sprintf(
                            $mandateTextForm,
                            Mage::getStoreConfig('payment/wirecardee_paymentgateway_sepadirectdebit/creditor_name')
                        );
                    }

                    echo $mandateText;
                    ?>
                </td>
            </tr>
        </table>
    </li>
    <li>
        <input type="checkbox" id="wirecardee-sepa--confirm-mandate"
               class="wirecardee--form-field"
               name="wirecardElasticEngine[sepaConfirmMandate]"
               required="required" value="confirmed"/>

        <label
            for="wirecardee-sepa--confirm-mandate"
            class="required"><?php echo $this->__('I have read and accepted the SEPA Direct Debit Mandate information.'); ?></label>
    </li>
</ul>
<script>
    jQuery(function ($) {
        $("[name^=wirecardElasticEngine]").on('keyup', function () {
            var firstname = $("#wirecardee-sepa--first-name").val(),
                lastname = $("#wirecardee-sepa--last-name").val(),
                iban = $("#wirecardee-sepa--iban").val(),
                bic = $("#wirecardee-sepa--bic").val();
            $("#wirecardee-sepa--first-last-name").text(firstname + " " + lastname);
            $("#wirecardee-sepa--bank-iban").text(iban);
            $("#wirecardee-sepa--bank-bic").text(bic);
        });
    });
</script>
