<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

/** @var WirecardEE_PaymentGateway_Block_Form $this */
$deviceFingerprintId = $this->getData('WirecardEEDeviceFingerprintId');
?>
    <div>
        <p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>
    </div>

<?php
if ($this->getMethod()->getCode() === 'wirecardee_paymentgateway_ratepayinvoice') {
    ?>
    <script language="JavaScript">
        var di = { t: "<?php echo $deviceFingerprintId; ?>", v: "WDWL", l: "Checkout" };
    </script>
    <script type="text/javascript" src="//d.ratepay.com/WDWL/di.js"></script>
    <noscript>
        <link rel="stylesheet" type="text/css"
              href="//d.ratepay.com/di.css?t=<?php echo $deviceFingerprintId; ?>&v=WDWL&l=Checkout">
    </noscript>
    <object type="application/x-shockwave-flash" data="//d.ratepay.com/WDWL/c.swf" width="0" height="0">
        <param name="movie" value="//d.ratepay.com/WDWL/c.swf"/>
        <param name="flashvars" value="t=<?php echo $deviceFingerprintId; ?>&v=WDWL"/>
        <param name="AllowScriptAccess" value="always"/>
    </object>
    <?php
}
?>

<?php
if ($this->getData('WirecardEEIncludeDeviceFingerprintIFrame')) {
    ?>
    <script type="text/javascript"
            src="https://h.wirecard.com/fp/tags.js?org_id=6xxznhva&session_id=<?php echo $deviceFingerprintId; ?>">
    </script>
    <noscript>
        <iframe style="width: 100px; height: 100px; border: 0; position: absolute; top: -5000px;"
                src="https://h.wirecard.com/tags?org_id=6xxznhva&session_id=<?php echo $deviceFingerprintId; ?>"></iframe>
    </noscript>
    <?php
}
