<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */

use WirecardEE\PaymentGateway\Service\Logger;

$wirecardUrl = $this->getData('wirecardUrl');
$requestData = $this->getData('wirecardRequestData');
$url         = $this->getData('url');

if (! $wirecardUrl || ! $requestData || ! $url) {
    (new Logger())->error('Unable to render template "' . $this->getTemplate() . '" due to missing variables"');
    echo Mage::helper('catalog')->__('Unable to render template');
    return;
}
?>
<div class="wirecardee-credit-card-error-message"
     style="display: none; margin-bottom: 20px; font-weight: bold; color: #ff0000;">
</div>
<div class="content content--checkout confirm--content">
    <form id="wirecardee-credit-card--form" method="post" action="<?php echo $url; ?>">
        <div id="wirecardee-credit-card--iframe-div" style="width: 100%; height: 550px;"></div>
        <button id="wirecardee-credit-card--form-submit"
                class="button btn-cart" type="submit">
            <?php echo Mage::helper('catalog')->__('submit_button'); ?>
        </button>
        <a class="button" style="background-color: #808080;"
           href="<?php echo Mage::getUrl('paymentgateway/gateway/cancel'); ?>">
            <?php echo Mage::helper('catalog')->__('cancel'); ?>
        </a>
    </form>
</div>

<script src="<?php echo $wirecardUrl; ?>/engine/hpp/paymentPageLoader.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        var $ = jQuery;
        var $formSubmit = $('#wirecardee-credit-card--form-submit');
        var $formSubmitIcon = $formSubmit.find('i');

        var handleFailedFormResponse = function (response) {
            $formSubmit.prop('disabled', false);
            $formSubmitIcon.attr('class', 'icon--arrow-right');
            if (response.transaction_state === 'failed') {
                $('.wirecardee-credit-card-error-message').html(response.status_description_1);
                $('.wirecardee-credit-card-error-message').show();
            }
        };

        WirecardPaymentPage.seamlessRenderForm({
            requestData: <?php echo $requestData; ?>,
            wrappingDivId: 'wirecardee-credit-card--iframe-div',
            onSuccess: handleFailedFormResponse,
            onError: handleFailedFormResponse
        });

        var setParentTransactionId = function (response) {
            var form = document.getElementById('wirecardee-credit-card--form'),
                formField = null;

            for (var key in response) {
                if (!response.hasOwnProperty(key)) {
                    continue;
                }
                formField = document.createElement('div');
                formField.innerHTML = '<input type="hidden" name="' + key + '" value="' + response[key] + '">';
                form.appendChild(formField);
            }

            formField = document.createElement('div');
            formField.innerHTML = '<input id="jsresponse" type="hidden" name="jsresponse" value="true">';
            form.appendChild(formField);
            form.submit();
        };

        document.getElementById('wirecardee-credit-card--form').addEventListener('submit', function (event) {
            // We check if the response fields are already set
            if (!document.getElementById('jsresponse')) {
                // If not, we will prevent the submission of the form and submit the credit card UI form instead
                event.preventDefault();
                // disable submit button and replace icon with loading spinner
                $formSubmit.prop('disabled', true);
                WirecardPaymentPage.seamlessSubmitForm({
                    wrappingDivId: 'wirecardee-credit-card--iframe-div',
                    onSuccess: function (response) {
                        setParentTransactionId(response);
                    },
                    onError: handleFailedFormResponse
                });
            }
        });
    });
</script>
