<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */
?>
<button
    id="payment_wirecardee_paymentgateway_<?php echo $this->getData('method'); ?>_check_credentials_button"
    type="button"
    onclick="WirecardEECheckCredentials('<?php echo $this->getData('method'); ?>');"
    data-base-url="<?php echo $this->getBaseUrl();?>"
    data-invalid-url-string="<?php echo Mage::helper('catalog')->__('wrong_url_format'); ?>"
    data-success-string="<?php echo Mage::helper('catalog')->__('success_credentials'); ?>"
    data-error-string="<?php echo Mage::helper('catalog')->__('error_credentials'); ?>"
>
    <?php echo Mage::helper('catalog')->__('test_credentials'); ?>
</button>
