<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento-ee/blob/master/LICENSE
 */
?>
<button
    id="payment_wirecardee_payment_gateway_<?php echo $this->getData('method'); ?>_check_credentials_button"
    type="button"
    onclick="WirecardEE_CheckCredentials('<?php echo $this->getData('method'); ?>');"
    data-invalid-url-string="<?php echo Mage::helper('catalog')->__('Invalid base URL'); ?>"
    data-success-string="<?php echo Mage::helper('catalog')->__('Success!'); ?>"
    data-error-string="<?php echo Mage::helper('catalog')->__('Error!'); ?>"
>
    <?php echo Mage::helper('catalog')->__('Test credentials'); ?>
</button>
